quarkus:
  vertx:
    cluster:
      clustered: false
  container-image:
    group: viewer
    name: server
    build: true
    additional-tags:
      - latest
  http:
    enable-compression: true
  quinoa:
    dev-server:
      port: 3000
      check-timeout: 20000
      managed: false
  datasource:
    jdbc: false
  hibernate-orm:
    statistics: true
    metrics:
      enabled: true
    physical-naming-strategy: "org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy"
    log:
      highlight-sql: true
      log:
        format-sql: true
        sql: true
  smallrye-openapi:
    enable: true
    store-schema-directory: build/openapi
  flyway:
    baseline-at-start: true
    baseline-description: first init
  package:
    jar:
      appcds:
        enable: true
"%dev":
  quarkus:
    log:
      category:
        "org.viewer":
          level: DEBUG
          min-level: DEBUG
        "org.hibernate":
          level: INFO
          min-level: INFO