quarkus:
  vertx:
    cluster:
      clustered: true
  container-image:
    group: guarder
    build: true
    additional-tags:
      - latest
  http:
    enable-compression: true
  quinoa:
    dev-server:
      port: 3000
      check-timeout: 20000
      managed: false
  datasource:
    jdbc: false
  hibernate-orm:
    physical-naming-strategy: "org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy"